tinyMCE.init({
    selector: "#mce",
    mode: "specific_textareas",
    height: 300,
    menubar: false,
    schema: "html5",
    plugins: "searchreplace,paste,advhr,table,insertdatetime",
    theme: "advanced",
    theme_advanced_buttons1: "bold,italic,underline,|,justifyleft,justifycenter,justifyright,|,forecolor,backcolor,|,fontselect,fontsizeselect,formatselect",
    theme_advanced_buttons2: "undo,redo,|,search,replace,|,bullist,numlist,|,outdent,indent,|,cut,copy,paste,pastetext,pasteword,selectall",
    theme_advanced_buttons3: "insertdate,inserttime,|,advhr,,removeformat,|,sub,sup,|,charmap,emotions,|,tablecontrols",
    theme_advanced_toolbar_location: "top",
    theme_advanced_toolbar_align: "left",
    theme_advanced_resizing: true,
    plugin_insertdate_dateFormat: "%d/%m/%Y",
    plugin_insertdate_timeFormat: "%H:%M:%S",
    paste_auto_cleanup_on_paste: true,
    table_styles: "Header 1=header1;Header 2=header2;Header 3=header3",
    table_cell_styles: "Header 1=header1;Header 2=header2;Header 3=header3;Table Cell=tableCel1",
    table_row_styles: "Header 1=header1;Header 2=header2;Header 3=header3;Table Row=tableRow1",
    table_cell_limit: 100,
    table_row_limit: 20,
    table_col_limit: 10
});